
package au.edu.unsw.soacourse.mds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.702+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "InvalidCurrencyCode", targetNamespace = "http://mds.soacourse.unsw.edu.au")
public class InvalidCurrencyCodeMsg extends Exception {
    
    private au.edu.unsw.soacourse.mds.ServiceFaultType invalidCurrencyCode;

    public InvalidCurrencyCodeMsg() {
        super();
    }
    
    public InvalidCurrencyCodeMsg(String message) {
        super(message);
    }
    
    public InvalidCurrencyCodeMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCurrencyCodeMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidCurrencyCode) {
        super(message);
        this.invalidCurrencyCode = invalidCurrencyCode;
    }

    public InvalidCurrencyCodeMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidCurrencyCode, Throwable cause) {
        super(message, cause);
        this.invalidCurrencyCode = invalidCurrencyCode;
    }

    public au.edu.unsw.soacourse.mds.ServiceFaultType getFaultInfo() {
        return this.invalidCurrencyCode;
    }
}
