
package au.edu.unsw.soacourse.mds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.725+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "InvalidDates", targetNamespace = "http://mds.soacourse.unsw.edu.au")
public class InvalidDatesMsg extends Exception {
    
    private au.edu.unsw.soacourse.mds.ServiceFaultType invalidDates;

    public InvalidDatesMsg() {
        super();
    }
    
    public InvalidDatesMsg(String message) {
        super(message);
    }
    
    public InvalidDatesMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDatesMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidDates) {
        super(message);
        this.invalidDates = invalidDates;
    }

    public InvalidDatesMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidDates, Throwable cause) {
        super(message, cause);
        this.invalidDates = invalidDates;
    }

    public au.edu.unsw.soacourse.mds.ServiceFaultType getFaultInfo() {
        return this.invalidDates;
    }
}
