
package au.edu.unsw.soacourse.mds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.679+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "InvalidFileType", targetNamespace = "http://mds.soacourse.unsw.edu.au")
public class InvalidFileTypeMsg extends Exception {
    
    private au.edu.unsw.soacourse.mds.ServiceFaultType invalidFileType;

    public InvalidFileTypeMsg() {
        super();
    }
    
    public InvalidFileTypeMsg(String message) {
        super(message);
    }
    
    public InvalidFileTypeMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidFileTypeMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidFileType) {
        super(message);
        this.invalidFileType = invalidFileType;
    }

    public InvalidFileTypeMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidFileType, Throwable cause) {
        super(message, cause);
        this.invalidFileType = invalidFileType;
    }

    public au.edu.unsw.soacourse.mds.ServiceFaultType getFaultInfo() {
        return this.invalidFileType;
    }
}
