
package au.edu.unsw.soacourse.mds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.734+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "InvalidURL", targetNamespace = "http://mds.soacourse.unsw.edu.au")
public class InvalidURLMsg extends Exception {
    
    private au.edu.unsw.soacourse.mds.ServiceFaultType invalidURL;

    public InvalidURLMsg() {
        super();
    }
    
    public InvalidURLMsg(String message) {
        super(message);
    }
    
    public InvalidURLMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidURLMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidURL) {
        super(message);
        this.invalidURL = invalidURL;
    }

    public InvalidURLMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType invalidURL, Throwable cause) {
        super(message, cause);
        this.invalidURL = invalidURL;
    }

    public au.edu.unsw.soacourse.mds.ServiceFaultType getFaultInfo() {
        return this.invalidURL;
    }
}
