package au.edu.unsw.soacourse.mds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.744+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://mds.soacourse.unsw.edu.au", name = "MarketDataServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MarketDataServices {

    @WebResult(name = "DownloadFileResp", targetNamespace = "http://mds.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://mds.soacourse.unsw.edu.au/downloadFile")
    public DownloadFileResp downloadFile(
        @WebParam(partName = "parameters", name = "DownloadFileReq", targetNamespace = "http://mds.soacourse.unsw.edu.au")
        DownloadFileReq parameters
    ) throws ProgramErrorMsg, InvalidFileTypeMsg, InvalidEventSetIdMsg;

    @WebResult(name = "ConvertMarketDataResp", targetNamespace = "http://mds.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://mds.soacourse.unsw.edu.au/convertMarketData")
    public ConvertMarketDataResp convertMarketData(
        @WebParam(partName = "parameters", name = "ConvertMarketDataReq", targetNamespace = "http://mds.soacourse.unsw.edu.au")
        ConvertMarketDataReq parameters
    ) throws ProgramErrorMsg, InvalidCurrencyCodeMsg, InvalidEventSetIdMsg;

    @WebResult(name = "ImportMarketDataResp", targetNamespace = "http://mds.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://mds.soacourse.unsw.edu.au/importMarketData")
    public ImportMarketDataResp importMarketData(
        @WebParam(partName = "parameters", name = "ImportMarketDataReq", targetNamespace = "http://mds.soacourse.unsw.edu.au")
        ImportMarketDataReq parameters
    ) throws ProgramErrorMsg, InvalidSECCodeMsg, InvalidDatesMsg, InvalidURLMsg;

    @WebResult(name = "YahooExchangeRateResp", targetNamespace = "http://mds.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://mds.soacourse.unsw.edu.au/yahooExchangeRate")
    public YahooExchangeRateResp yahooExchangeRate(
        @WebParam(partName = "parameters", name = "YahooExchangeRateReq", targetNamespace = "http://mds.soacourse.unsw.edu.au")
        YahooExchangeRateReq parameters
    ) throws ProgramErrorMsg, InvalidCurrencyCodeMsg;
}
