package au.edu.unsw.soacourse.mds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.763+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "MarketDataServices", 
                  wsdlLocation = "file:/C:/J2EEWorkspace/MarketDataServices/src/main/resources/wsdl/MarketDataServices.wsdl",
                  targetNamespace = "http://mds.soacourse.unsw.edu.au") 
public class MarketDataServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mds.soacourse.unsw.edu.au", "MarketDataServices");
    public final static QName MarketDataServicesSOAP = new QName("http://mds.soacourse.unsw.edu.au", "MarketDataServicesSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/J2EEWorkspace/MarketDataServices/src/main/resources/wsdl/MarketDataServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MarketDataServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/J2EEWorkspace/MarketDataServices/src/main/resources/wsdl/MarketDataServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MarketDataServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MarketDataServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketDataServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MarketDataServices_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MarketDataServices_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MarketDataServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MarketDataServices
     */
    @WebEndpoint(name = "MarketDataServicesSOAP")
    public MarketDataServices getMarketDataServicesSOAP() {
        return super.getPort(MarketDataServicesSOAP, MarketDataServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketDataServices
     */
    @WebEndpoint(name = "MarketDataServicesSOAP")
    public MarketDataServices getMarketDataServicesSOAP(WebServiceFeature... features) {
        return super.getPort(MarketDataServicesSOAP, MarketDataServices.class, features);
    }

}
