
package au.edu.unsw.soacourse.mds;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-04-13T13:23:39.651+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "ProgramError", targetNamespace = "http://mds.soacourse.unsw.edu.au")
public class ProgramErrorMsg extends Exception {
    
    private au.edu.unsw.soacourse.mds.ServiceFaultType programError;

    public ProgramErrorMsg() {
        super();
    }
    
    public ProgramErrorMsg(String message) {
        super(message);
    }
    
    public ProgramErrorMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ProgramErrorMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType programError) {
        super(message);
        this.programError = programError;
    }

    public ProgramErrorMsg(String message, au.edu.unsw.soacourse.mds.ServiceFaultType programError, Throwable cause) {
        super(message, cause);
        this.programError = programError;
    }

    public au.edu.unsw.soacourse.mds.ServiceFaultType getFaultInfo() {
        return this.programError;
    }
}
